apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "momo-frontend.name" . }}-config
  labels:
    {{- include "momo-frontend.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env.config }}
  {{ $key }}: "{{ $value }}"
{{- end }}
