apiVersion: v1
kind: Service
metadata:
  name: {{ include "momo-frontend.fullname" . }}
  labels:
    {{- include "momo-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
      {{- include "momo-frontend.selectorLabels" . | nindent 6 }}
